CREATE TABLE "ISPIEGEL_VERGELIJKING"
(	"VERGELIJKINGNAAM" VARCHAR(255) NOT NULL,
	"REFERENTIEDATABRONNAAM" VARCHAR(255),
	"ANALYSEDATABRONNAAM" VARCHAR(255),
	"VELDTOEWIJZING" TEXT,
	"ROLCOGNOSBEKIJKANALYSE" VARCHAR(255), 
	"ROLCOGNOSBEKIJKREFERENTIE" VARCHAR(255), 
	"ACTIEF" NUMERIC NOT NULL,
	"RAPPORTTYPE" VARCHAR(255), 
	 CONSTRAINT "ISPIEGEL_VERGELIJKING_PK" PRIMARY KEY ("VERGELIJKINGNAAM")
);

CREATE TABLE "ISPIEGEL_CONTROLE"
(	"CONTROLENAAM" VARCHAR(255) NOT NULL,
	"DATABRONNAAM" VARCHAR(255),
	"CONTROLEKOLOM" VARCHAR(255),
	"SLEUTELKOLOM" VARCHAR(255),
	"CONTROLEWAARDE" VARCHAR(255),
	"ROLCOGNOSBEKIJKANALYSE" VARCHAR(255), 
	"ROLCOGNOSBEKIJKREFERENTIE" VARCHAR(255), 
 	"RAPPORTTYPE" VARCHAR(255), 
	"ACTIEF" NUMERIC NOT NULL,
	 CONSTRAINT "ISPIEGEL_CONTROLE_PK" PRIMARY KEY ("CONTROLENAAM")
);

CREATE TABLE "ISPIEGEL_DATABRON"
(	"DATABRONNAAM" VARCHAR(255) NOT NULL,
	"APPLICATIENAAM" VARCHAR(255),
	"GEMEENTECODE" VARCHAR(255),
	"PROVIDER" VARCHAR(255),
	"CONNECTIONSTRING" VARCHAR(255),
	"QUERY" TEXT,
	"ESCAPESEQUENCE" VARCHAR(255),
	 CONSTRAINT "ISPIEGEL_DATABRON_PK" PRIMARY KEY ("DATABRONNAAM")
);

CREATE TABLE "ISPIEGEL_OUTPUT"
(	"OUTPUTID" NUMERIC NOT NULL,
	"TIJDSTIP" DATE,
	"VERGELIJKINGNAAM" VARCHAR(255),
	"CONFIGURATIE" TEXT,
	"REFERENTIENAAM" VARCHAR(255),
	"ANALYSENAAM" VARCHAR(255),
	"REFERENTIEQUERY" TEXT,
	"ANALYSEQUERY" TEXT,
	"REFERENTIEAPPLICATIE" VARCHAR(255),
	"ANALYSEAPPLICATIE" VARCHAR(255),
	"REFERENTIEGEMEENTECODE" VARCHAR(255),
	"ANALYSEGEMEENTECODE" VARCHAR(255),
	"PERCENTAGE" FLOAT,
	"REFERENTIEAANTAL" NUMERIC,
	"ANALYSEAANTAL" NUMERIC,
	"GELIJKAANTAL" NUMERIC,
	"AFWIJKINGAANTAL" NUMERIC,
	"NIETGEVONDENAANTAL" NUMERIC,
	"LOOPTIJD" NUMERIC,
        "RAPPORTTYPE" VARCHAR(255), 
	 CONSTRAINT "ISPIEGEL_OUTPUT_PK" PRIMARY KEY ("OUTPUTID")
);
CREATE TABLE "ISPIEGEL_OUTPUTLINE"
 (	"OUTPUTID" NUMERIC NOT NULL,
	"REGELNUMMER" NUMERIC NOT NULL,
	"STATUS" VARCHAR(255),
	"CONTROLE" VARCHAR(255),
	"ANALYSESLEUTELWAARDE" VARCHAR2(255),
	"ANALYSEVELDWAARDE" VARCHAR2(255),
	"REFERENTIESLEUTELWAARDE" VARCHAR2(255),
	"REFERENTIEVELDWAARDE" VARCHAR2(255),
	"SLEUTEL" TEXT,
	"ANALYSEWAARDE" TEXT,
	"REFERENTIEWAARDE" TEXT,
	"ANALYSEREGEL" TEXT,
	"REFERENTIEREGEL" TEXT,
	 CONSTRAINT "ISPIEGEL_OUTPUTLINE_PK" PRIMARY KEY ("OUTPUTID", "REGELNUMMER")
);
