-- Nieuw t.b.v. package 1.0
alter table ISPIEGEL_OUTPUTLINE
add ( ANALYSESLEUTELWAARDE VARCHAR2(255 BYTE));

alter table ISPIEGEL_OUTPUTLINE
add ( ANALYSEVELDWAARDE VARCHAR2(255 BYTE));

alter table ISPIEGEL_OUTPUTLINE
add (REFERENTIESLEUTELWAARDE VARCHAR2(255 BYTE));

alter table ISPIEGEL_OUTPUTLINE
add (REFERENTIEVELDWAARDE VARCHAR2(255 BYTE));

-- ********** Nieuw t.b.v. package 2.0 d.d. 30-10-2019 **********

-- Toevoegen kolommen voor toegangsrechten

-- Toevoegen 3 nieuwe kolommen aan ISPIEGEL_VERGELIJKING
-- Indien deze nog niet bestaat:
alter table ISPIEGEL_VERGELIJKING
add (RAPPORTTYPE VARCHAR2(255 BYTE));

alter table ISPIEGEL_VERGELIJKING
add (ROLCOGNOSBEKIJKANALYSE VARCHAR2(255 BYTE));

alter table ISPIEGEL_VERGELIJKING
add (ROLCOGNOSBEKIJKREFERENTIE VARCHAR2(255 BYTE));

-- Toevoegen 2 nieuwe kolommen aan ISPIEGEL_CONTROLE
alter table ISPIEGEL_CONTROLE
add (ROLCOGNOSBEKIJKANALYSE VARCHAR2(255 BYTE));

alter table ISPIEGEL_CONTROLE
add (RAPPORTTYPE  VARCHAR2(255 BYTE));

-- Toevoegen 1 nieuwe kolom aan ISPIEGEL_OUTPUT
alter table ISPIEGEL_OUTPUT
add (RAPPORTTYPE  VARCHAR2(255 BYTE));

-- Aanmaken index ivm 1e signalering van een bevinding
CREATE INDEX "ISPIEGEL"."ISPIEGEL_OUTPUTLINEI1" ON "ISPIEGEL"."ISPIEGEL_OUTPUTLINE" ("ANALYSESLEUTELWAARDE", "OUTPUTID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "ISPIEGEL" ;

CREATE INDEX "ISPIEGEL"."ISPIEGEL_OUTPUTI1" ON "ISPIEGEL"."ISPIEGEL_OUTPUT" ("VERGELIJKINGNAAM", "OUTPUTID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "ISPIEGEL" ;
