/*
O7.1:
	Debiteurenregistratie - adressen van actuele dubieuze debiteuren ondernemingen

	Contact: A.vanderSchaar@gemeenteswf.nl

	Adresseerbaar object ID	
	Nummeraanduiding ID	
	Openbare ruimte ID	
	Straatnaam / Naam openbare ruimte*	
	Woonplaatsnaam*	
	Postcode*	
	Huisnummer*	
	Huisletter*	
	Huisnummertoevoeging*	
	Bedrag openstaande vorderingen*	
	Datum aanslag nota*
*/
SELECT FIS_VDEBITEUREN.NATUURLIJK_NIET_NATUURLIJK,
  FIS_VDEBITEUREN.VOORLETTERS,
  FIS_VDEBITEUREN.VOORVOEGSEL,
  FIS_VDEBITEUREN.NAAM,
  FIS_VDEBITEUREN.STRAATNAAM,
  FIS_VDEBITEUREN.HUISNUMMER,
  FIS_VDEBITEUREN.HUISLETTER,
  FIS_VDEBITEUREN.TOEVOEGING_HUISNUMMER,
  FIS_VDEBITEUREN.POSTKODE_NUMERIEK
  || FIS_VDEBITEUREN.POSTKODE_ALFANUMERIEK AS POSTCODE,
  FIS_VDEBITEUREN.PLAATSNAAM,
  FIS_TNOTASOORTEN.KODE_NOTASOORT,
  FIS_TNOTA.AANSLAGNUMMER,
  FIS_TNOTA.STAMNUMMER_BELASTINGADM,
  FIS_TNOTA.NOTANUMMER,
  FIS_TNOTA.EUR_TOT_BEDR_NOTA,
  FIS_TNOTA.EUR_OPENST_BEDR,
  FIS_TNOTA.EUR_TOT_BEDR_NOTA - FIS_TNOTA.EUR_OPENST_BEDR AS AFBETAALD,
  FIS_TNOTA.DIENSTJAAR,
  FIS_TNOTA.OPVOERDATUM,
  FIS_TTERMIJNSCHRGLS.DAGTEKENING_AANMANING,
  FIS_TTERMIJNSCHRGLS.DAGTEKENING_DWANGBEVEL,
  FIS_TTERMIJNSCHRGLS.DATUM_1E_HERINNERING,
  FIS_TTERMIJNSCHRGLS.DATUM_2E_HERINNERING,
  FIS_TTERMIJNSCHRGLS.DATUM_3E_HERINNERING,
  FIS_TNOTA.PERIODE_GROOTBOEK,
  FIS_TNOTA.BEDRIJFSKODE,
  FIS_TONTVANGSTEN.EUR_BEDR,
  FIS_VDEBITEUREN.NATUURLIJK_NIET_NATUURLIJK,
  FIS_VDEBITEUREN.KVK_NUMMER_1  
FROM FIS_VDEBITEUREN@PFIS FIS_VDEBITEUREN
LEFT OUTER JOIN BAG_ACTUELE_WOONPLAATSEN
ON BAG_ACTUELE_WOONPLAATSEN.UWOONPLAATSNAAM = FIS_VDEBITEUREN.PLAATSNAAM,
  FIS_TNOTASOORTEN@PFIS FIS_TNOTASOORTEN,
  FIS_TTERMIJNSCHEMA@PFIS FIS_TTERMIJNSCHEMA,
  FIS_TTERMIJNSCHRGLS@PFIS FIS_TTERMIJNSCHRGLS,
  FIS_TNOTA@PFIS FIS_TNOTA
LEFT OUTER JOIN FIS_TONTVANGSTEN@PFIS FIS_TONTVANGSTEN
ON FIS_TNOTA.NOTANUMMER_INTERN           = FIS_TONTVANGSTEN.NOTANUMMER_INTERN
AND FIS_TNOTA.BEDRIJFSKODE               = FIS_TONTVANGSTEN.BEDRIJFSKODE_NTA
WHERE FIS_TNOTA.DEBITEURENNUMMER         = FIS_VDEBITEUREN.DEBITEURENNUMMER
AND FIS_TNOTA.NAW_RELATIE_NUMMER         = FIS_VDEBITEUREN.NAW_RELATIE_NUMMER
AND FIS_TNOTA.BEDRIJFSKODE_DBR           = FIS_VDEBITEUREN.BEDRIJFSKODE
AND FIS_TNOTA.BEDRIJFSKODE               = FIS_TTERMIJNSCHEMA.BEDRIJFSKODE_NTA
AND FIS_TNOTA.NOTANUMMER_INTERN          = FIS_TTERMIJNSCHEMA.NOTANUMMER_INTERN
AND FIS_TTERMIJNSCHEMA.BEDRIJFSKODE_NTS  = FIS_TNOTASOORTEN.BEDRIJFSKODE
AND FIS_TTERMIJNSCHEMA.NOTASOORT         = FIS_TNOTASOORTEN.KODE_NOTASOORT
AND FIS_TTERMIJNSCHEMA.NOTANUMMER_INTERN = FIS_TNOTA.NOTANUMMER_INTERN
AND FIS_TTERMIJNSCHEMA.BEDRIJFSKODE_NTA  = FIS_TNOTA.BEDRIJFSKODE
AND FIS_TTERMIJNSCHEMA.BEDRIJFSKODE      = FIS_TTERMIJNSCHRGLS.BEDRIJFSKODE
AND FIS_TTERMIJNSCHEMA.NOTANUMMER_INTERN = FIS_TTERMIJNSCHRGLS.NOTANUMMER_INTERN
AND FIS_TTERMIJNSCHEMA.VOLGNR            = FIS_TTERMIJNSCHRGLS.VOLGNR_TSC
AND FIS_TNOTA.EUR_OPENST_BEDR          <> 0.00
AND FIS_TNOTA.BEDRIJFSKODE               = 10
AND 'J'                                 <> FIS_TTERMIJNSCHEMA.VERVALLEN
AND 
(
  BAG_ACTUELE_WOONPLAATSEN.GEMEENTECODE = 1900 
  OR 
  BAG_ACTUELE_WOONPLAATSEN.GEMEENTECODE IS NULL
)