/*
OC:
	GBA - adressen van actuele personen
	
	Contact: A.Kraak@gemeenteswf.nl

	Adresseerbaar object ID	
	Nummeraanduiding ID	
	Openbare ruimte ID	
	Naam openbare ruimte*	
	Woonplaatsnaam*	
	Postcode*	
	Huisnummer*	
	Huisletter*	
	Huisnummertoevoeging*
*/
SELECT 
  GBA_VSELAKTP."BSN",
  GBA_VSELAKTP."GEBOORTEDATUM", 
  GBA_VSELAKTP."VOORLETTERS", 
  GBA_VSELAKTP."VOORVOEGSEL", 
  GBA_VSELAKTP."GESLACHTSNAAM", 
  GBA_VSELAKTP."GEMEENTEKODE", 
  GBA_VSELAKTP."STRAATNAAM", 
  GBA_VSELADRS."NAAM_OPENBARE_RUIMTE", 
  GBA_VSELAKTP."HUISNUMMER", 
  GBA_VSELAKTP."HUISLETTER", 
  GBA_VSELAKTP."TOEVOEGING_HUISNUMMER", 
  GBA_VSELAKTP."AANDUIDING_HUISNUMMER", 
  GBA_VSELAKTP."OMSCHRIJVING_LOKATIE", 
  GBA_VSELAKTP."POSTKODE_NUMERIEK" || GBA_VSELAKTP."POSTKODE_ALFANUMERIEK" AS POSTCODE, 
  GBA_VSELADRS."GEMEENTEDEEL" AS WOONPLAATS,
  GBA_VSELADRS."IDENT_VERBLIJFPLAATS", 
  GBA_VSELADRS."IDENT_NUMMERAANDUIDING"
FROM
  "PRODPIV"."GBA_VSELAKTP"@PPIV,
  "PRODPIV"."GBA_VSELADRS"@PPIV
WHERE GBA_VSELAKTP."SYSTEEMNUMMER_ADRES" = GBA_VSELADRS."SYSTEEMNUMMER_ADRES"