/*
	OZB - aanslagen lokale belastingen zonder kwijtschelding aangevraagd
	
	Contact: A.vanderSchaar@gemeenteswf.nl
	
	A-nummer	
	BSN*	
	Voorvoegsel*	
	Geslachtsnaam*	
	Geboortedatum*	
	Geboorteplaats*	
	Geslacht*	
	Postcode*	
	Straatnaam	
	Huisnummer*	
	Huisletter*	
	Huisnummertoevoeging*

*/
SELECT INN_VIMP_FINVERANTWOORDING.KODE_GEBRUIKER,
  INN_VIMP_FINVERANTWOORDING.SOORT_AANSLAGBILJET,
  INN_VIMP_FINVERANTWOORDING.HEFFINGJAAR,
  INN_VIMP_FINVERANTWOORDING.AANSLAGBILJSERIE_NUMMER,
  INN_VIMP_FINVERANTWOORDING.AANSLAGBILJET_NUMMER,
  INN_VIMP_FINVERANTWOORDING.KODE_FINVERANTWOORDING_CAT,
  INN_VIMP_FINVERANTWOORDING.KODE_FINVERANTWOORDING,
  INN_VIMP_FINVERANTWOORDING.VOLGNUMMER_FINVERANTWOORDING,
  INN_VIMP_FINVERANTWOORDING.SOORT_AFBOEKING,
  INN_VIMP_FINVERANTWOORDING.VALUTADATUM,
  INN_VIMP_FINVERANTWOORDING.OPGEMAAKTE_VALUTADATUM,
  INN_VIMP_FINVERANTWOORDING.BEDRAG,
  INN_VIMP_FINVERANTWOORDING.MUTATIENUMMER,
  INN_VIMP_FINVERANTWOORDING.MUTATIEDATUM,
  PVS_VIMP_VERGUNNING.PRODUCTNUMMER,
  SUB_VIMP_SUBJECT.SUBJECTNUMMER,
  SUB_VIMP_SUBJECT.ANUMMER,
  SUB_VIMP_SUBJECT.BURGERSERVICENUMMER,
  SUB_VIMP_SUBJECT.VOORVOEGSEL,
  SUB_VIMP_SUBJECT.VOORLETTER,
  SUB_VIMP_SUBJECT.NAAM,
  SUB_VIMP_SUBJECT.GEBOORTEDATUM,
  NULL AS GEBOORTEPLAATS,
  SUB_VIMP_SUBJECT.GESLACHT,
  SUB_VIMP_SUBJECT_ADRES.OMS_ADRESSOORT,
  ADR_VIMP_ADRES.STRAATNAAM,
  ADR_VIMP_ADRES.HUISNUMMER,
  ADR_VIMP_ADRES.HUISNUMMER_LETTER,
  ADR_VIMP_ADRES.HUISNUMMER_TOEVOEGING,
  ADR_VIMP_ADRES.HUISNUMMER_AANDUIDING,
  ADR_VIMP_ADRES.POSTCODE_NUMMER || ADR_VIMP_ADRES.POSTCODE_LETTER AS POSTCODE,
  ADR_VIMP_ADRES.GEMEENTEKODE,
  ADR_VIMP_ADRES.GEMEENTENAAM,
  ADR_VIMP_ADRES.WOONPLAATS,
  PVS_VIMP_VERGUNNINGREGEL.REGELNUMMER_KWITANTIE,
  SUB_VIMP_SUBJECT_ADRES.SYSTEEMNUMMER_ADRES
FROM INN_VIMP_FINVERANTWOORDING@PPAR INN_VIMP_FINVERANTWOORDING
LEFT JOIN PVS_VIMP_VERGUNNINGREGEL@PPAR PVS_VIMP_VERGUNNINGREGEL
  ON PVS_VIMP_VERGUNNINGREGEL.KODE_GEBRUIKER              = INN_VIMP_FINVERANTWOORDING.KODE_GEBRUIKER
  AND PVS_VIMP_VERGUNNINGREGEL.AANSLAGBILJETSERIE_INN4U   = INN_VIMP_FINVERANTWOORDING.AANSLAGBILJSERIE_NUMMER
  AND PVS_VIMP_VERGUNNINGREGEL.AANSLAGBILJET_NUMMER_INN4U = INN_VIMP_FINVERANTWOORDING.AANSLAGBILJET_NUMMER
LEFT JOIN PVS_VIMP_VERGUNNING@PPAR PVS_VIMP_VERGUNNING
  ON PVS_VIMP_VERGUNNING.KODE_GEBRUIKER = PVS_VIMP_VERGUNNINGREGEL.KODE_GEBRUIKER
  AND PVS_VIMP_VERGUNNING.PRODUCTNUMMER = PVS_VIMP_VERGUNNINGREGEL.PRODUCTNUMMER
LEFT JOIN SUB_VIMP_SUBJECT@PPAR SUB_VIMP_SUBJECT
  ON SUB_VIMP_SUBJECT.KODE_GEBRUIKER = PVS_VIMP_VERGUNNING.KODE_GEBRUIKER
  AND SUB_VIMP_SUBJECT.SUBJECTNUMMER = PVS_VIMP_VERGUNNING.SUBJECTNUMMER
LEFT JOIN SUB_VIMP_SUBJECT_ADRES@PPAR SUB_VIMP_SUBJECT_ADRES
  ON SUB_VIMP_SUBJECT_ADRES.KODE_GEBRUIKER = SUB_VIMP_SUBJECT.KODE_GEBRUIKER
  AND SUB_VIMP_SUBJECT_ADRES.SUBJECTNUMMER = SUB_VIMP_SUBJECT.SUBJECTNUMMER
LEFT JOIN ADR_VIMP_ADRES@PPAR ADR_VIMP_ADRES
  ON ADR_VIMP_ADRES.KODE_GEBRUIKER                        = SUB_VIMP_SUBJECT_ADRES.KODE_GEBRUIKER
  AND ADR_VIMP_ADRES.SYSTEEMNUMMER_ADRES                  = SUB_VIMP_SUBJECT_ADRES.SYSTEEMNUMMER_ADRES
WHERE INN_VIMP_FINVERANTWOORDING.KODE_FINVERANTWOORDING = 'AOEW'