CREATE TABLE REGISTRATIEVERGELIJKING
(	
  REGISTRATIEVERGELIJKINGID NUMBER NOT NULL, 
	TIJDSTIP DATE, 
	VERGELIJKING VARCHAR2(1024 BYTE), 
	CONFIGURATIE CLOB, 
	PERCENTAGE NUMBER, 
	REFERENTIEAANTAL NUMBER, 
	ANALYSEAANTAL NUMBER, 
	GELIJKAANTAL NUMBER, 
	AFWIJKINGAANTAL NUMBER, 
	NIETGEVONDENAANTAL NUMBER, 
	LOOPTIJD DATE, 
   
	CONSTRAINT "REGISTRATIEVERGELIJKING_PK" PRIMARY KEY ("REGISTRATIEVERGELIJKINGID")
);

CREATE TABLE registatievergelijkingregel
(       
	REGISTRATIEVERGELIJKINGID NUMBER NOT NULL,
	regelnummer NUMBER NOT NULL,
	status CLOB,
	melding CLOB,
	referentieregel CLOB,
	analyseregel  CLOB,
	
	CONSTRAINT registatievergelijkingregel_pk PRIMARY KEY (REGISTRATIEVERGELIJKINGID, regelnummer)
);