CREATE TABLE "GEGEVENSBEHEER"."REGISTRATIEVERGELIJKING" 
(	"REGISTRATIEVERGELIJKINGID" NUMBER NOT NULL, 
	"TIJDSTIP" DATE, 
	"VERGELIJKING" VARCHAR2(1024 BYTE), 
	"CONFIGURATIE" CLOB, 
	"PERCENTAGE" NUMBER, 
	"REFERENTIEAANTAL" NUMBER, 
	"ANALYSEAANTAL" NUMBER, 
	"GELIJKAANTAL" NUMBER, 
	"AFWIJKINGAANTAL" NUMBER, 
	"NIETGEVONDENAANTAL" NUMBER, 
	"LOOPTIJD" DATE, 
	 CONSTRAINT "REGISTRATIEVERGELIJKING_PK" PRIMARY KEY ("REGISTRATIEVERGELIJKINGID")
);
CREATE TABLE "GEGEVENSBEHEER"."REGISTRATIEVERGELIJKING" 
(	"REGISTRATIEVERGELIJKINGID" NUMBER NOT NULL ENABLE, 
	"TIJDSTIP" DATE, 
	"VERGELIJKING" VARCHAR2(1024 BYTE), 
	"CONFIGURATIE" CLOB, 
	"PERCENTAGE" NUMBER, 
	"REFERENTIEAANTAL" NUMBER, 
	"ANALYSEAANTAL" NUMBER, 
	"GELIJKAANTAL" NUMBER, 
	"AFWIJKINGAANTAL" NUMBER, 
	"NIETGEVONDENAANTAL" NUMBER, 
	"LOOPTIJD" DATE, 
	 CONSTRAINT "REGISTRATIEVERGELIJKING_PK" PRIMARY KEY ("REGISTRATIEVERGELIJKINGID")
);